version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: matcha-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matcha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d matcha || exit 1"]
      interval: 3s
      timeout: 5s
      retries: 20
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:latest
    container_name: matcha-mailhog
    ports:
      - "1025:1025"  # SMTP
      - "8025:8025"  # Web UI
    restart: unless-stopped

volumes:
  pgdata: {}
